version: "3"
services:
  app:
    build: .
    volumes:
      - ./:/opt/server
    ports:
      - 8000:8000
    links:
      - database
  database:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepassword
